---
stages:
  - build
  - docker
  - acceptance

build:
  stage: build
  image: golang:1.23.4
  before_script:
    - apt-get update && apt-get install -y wget
    - wget https://github.com/go-swagger/go-swagger/releases/download/v0.30.5/swagger_linux_amd64 -O /usr/local/bin/swagger
    - chmod +x /usr/local/bin/swagger
  script:
    - swagger generate server -f ./swagger.yml --exclude-main
    - make build
  artifacts:
    paths:
      - target/bin/carpool

dockerize:
  stage: docker
  dependencies:
    - build
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375/
  services:
    - docker:dind
  script:
    - echo ${CI_JOB_TOKEN} | docker login --password-stdin -u ${CI_REGISTRY_USER} ${CI_REGISTRY}
    - docker build . -t ${CI_REGISTRY_IMAGE}:latest
    - docker push ${CI_REGISTRY_IMAGE}:latest
    - docker inspect ${CI_REGISTRY_IMAGE}:latest | grep -A 10 "Config"

acceptance:
  image: cabify/challenge:latest
  stage: acceptance
  dependencies: []
  services:
    - name: ${CI_REGISTRY_IMAGE}:latest
      alias: pooling
  script:
    - /harness --address http://pooling:9091 acceptance
