version: '3'

services:
  pooling:
    image: car-pooling-challenge:latest
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://pooling:8080/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10

  harness:
    image: cabify/challenge:latest
    command: /harness --address http://pooling:8080 acceptance
    depends_on:
      pooling:
        condition: service_healthy